name: playground
on:
  push:
    paths: 
      - .github/workflows/playground.yml

jobs:
  azure:
    runs-on: windows-latest
    steps:
      - name: Azure DevOps Login
        env: 
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}
        shell: cmd
        run: |
          az devops login --organization https://dev.azure.com/lxbndr/

  rev-store:
    runs-on: windows-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Store Rev
        shell: cmd
        run: |
          mkdir i
          git rev-parse HEAD > i\rev.txt

      - name: Upload Rev
        uses: actions/upload-artifact@v1
        with:
          name: rev
          path: i

  rev-read:
    needs: [rev-store]
    runs-on: windows-latest

    steps:
      - name: Download Rev
        uses: actions/download-artifact@v1
        with:
          name: rev
          path: 'a'
      - name: Read Rev
        shell: cmd
        run: |
          set /p SW_REV=< a\rev.txt
          echo Rev is %SW_REV%
