name: playground
on:
  push:
    paths: 
      - .github/workflows/playground.yml
  
jobs:
  icu:
    runs-on: windows-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Configure Build Environment
        shell: cmd
        run: |
          git rev-parse HEAD > rev.txt
          set /p SW_REV=< rev.txt
          
          echo REv is %SW_REV%
         
