name: playground
on:
  push:
    paths: 
      - .github/workflows/playground.yml

env:
  SW_ICU_VERSION: 64
  
jobs:
  icu:
    runs-on: windows-latest
    env:
      INSTALL_PATH: i\icu-${{ env.SW_ICU_VERSION }}\usr

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Checkout ICU
        uses: actions/checkout@v2
        with:
          repository: 'unicode-org/icu'
          ref: 'maint/maint-${{ env.SW_ICU_VERSION }}'
          fetch-depth: 1
          path: 'icu'
      - name: Configure Build Environment
        shell: cmd
        run: |
          call .github\workflows\vsenv.cmd -arch=x64 -host_arch=x64
          
          set SW_INSTALL_PATH=%GITHUB_WORKSPACE%\i\Library\icu-%SW_ICU_VERSION%\usr
          echo ::set-env name=SW_INSTALL_PATH::%SW_INSTALL_PATH%
          copy %GITHUB_WORKSPACE%\cmake\ICU\CMakeLists.txt icu\icu4c
      - name: Configure ICU
        shell: cmd
        run: |
          subst T: "%GITHUB_WORKSPACE%\icu\icu4c"
          cmake^
           -G Ninja^
           -S T:\^
           -B %GITHUB_WORKSPACE%\b^
           -C %GITHUB_WORKSPACE%\cmake\caches\windows-x86_64.cmake^
           -DCMAKE_BUILD_TYPE=MinSizeRel^
           -DCMAKE_INSTALL_PREFIX=%SW_INSTALL_PATH%^
           -DBUILD_SHARED_LIBS=YES^
           -DBUILD_TOOLS=YES
