name: swift-win-x64-vs2019

on: [push]

jobs:
  icu:

    runs-on: windows-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Checkout ICU
        uses: actions/checkout@v2
        with:
          repository: 'unicode-org/icu'
          ref: 'maint/maint-64'
          fetch-depth: 1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  curl:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
  xml2:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
          
  zlib:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
  toolchain:
    
    needs: [icu, curl, xml2, zlib]
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
  sdk:
    
    needs: [toolchain]
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
