name: swift-snapshot-trigger

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  
  trigger-snapshot:
    runs-on: ubuntu-latest
    if: (contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '@ci test')) || github.event_name == 'workflow_dispatch'

    strategy:
      fail-fast: false
      matrix:
        spec: ['main', '5.4', '5.3']

    steps:
      - name: Trigger `${{ matrix.spec }}` Workflow
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: readdle
          repo: swift-windows-gha
          workflow_id: swift-snapshot.yml
          ref: ${{ github.ref }}
          inputs: '{ "branch-spec": "${{ matrix.spec }}" }'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
