name: swift-win-x64-vs2019

on: [push]

jobs:
  icu:

    runs-on: windows-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Checkout ICU
        uses: actions/checkout@v2
        with:
          repository: 'unicode-org/icu'
          ref: 'maint/maint-64'
          fetch-depth: 1
          path: 'icu'
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  curl:

    runs-on: windows-latest
    needs: [zlib]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout curl
        uses: actions/checkout@v2
        with:
          repository: 'curl/curl'
          ref: 'master'
          fetch-depth: 1
          path: 'curl'
      - name: Run a one-line script
        run: echo Hello, world!

  libxml2:

    runs-on: windows-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Checkout libxml2
        uses: actions/checkout@v2
        with:
          repository: 'compnerd/libxml2'
          ref: 'cmake'
          fetch-depth: 1
          path: 'libxml2'
      - name: Run a one-line script
        run: echo Hello, world!

  zlib:

    runs-on: windows-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Checkout zlib
        uses: actions/checkout@v2
        with:
          repository: 'madler/zlib'
          ref: 'refs/tags/v1.2.11'
          fetch-depth: 1
          path: 'zlib'
      - name: Run a one-line script
        run: echo Hello, world!

  toolchain:

    runs-on: windows-latest
    needs: [icu]
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config --global --add core.autocrlf false
          git config --global --add core.symlinks true
      - name: Checkout LLVM
        uses: actions/checkout@v2
        with:
          repository: 'apple/llvm-project'
          ref: 'swift/master'
          fetch-depth: 1
          path: 's/toolchain' 
      - name: Checkout cmark
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-cmark'
          ref: 'master'
          fetch-depth: 1
          path: 's/toolchain/cmark' 
      - name: Checkout libdispatch
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-corelibs-libdispatch'
          ref: 'master'
          fetch-depth: 1
          path: 's/swift-corelibs-libdispatch' 
      - name: Checkout swift
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift'
          ref: 'master'
          fetch-depth: 1
          path: 's/toolchain/swift'

  sdk:
    
    runs-on: windows-latest
    needs: [icu, curl, libxml2, toolchain]
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!

