name: swift-master
on:
  push:
    paths-ignore: 
      - .github/workflows/swift-5.3.yml
      - .github/workflows/swift-build-script.yml
      - LICENSE
      - README.md

  schedule:
    - cron: '0 22 * * *'

env:
  SW_SWIFT_BRANCH_SPEC: master
  SW_CURL_VERSION: development
  SW_ICU_VERSION: 67
  SW_XML2_VERSION: development
  SW_ZLIB_VERSION: 1.2.11
  SW_WORKSPACE: ${{ github.workspace }}
  SW_SOURCES_DIR: ${{ github.workspace }}\s
  SW_BUILD_DIR: ${{ github.workspace }}\b
  SW_INSTALL_DIR: ${{ github.workspace }}\i
  SW_ARTIFACTS_DIR: ${{ github.workspace }}\a

jobs:
  icu:

    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Configure Build Environment
        run: |
          call scripts\tools\init-build.cmd
          call scripts\workflows\jobs\steps\icu\configure-build-environment.cmd

      - name: Checkout ICU
        uses: actions/checkout@v2
        with:
          repository: 'unicode-org/icu'
          ref: '${{ env.SW_ICU_REF }}'
          fetch-depth: 1
          path: '${{ env.SW_ICU_SOURCES_DIR }}'

      - name: Patch ICU
        run: scripts\workflows\jobs\steps\icu\patch-icu.cmd

      - name: Configure ICU
        run: scripts\workflows\jobs\steps\icu\configure-icu.cmd

      - name: Build ICU
        run: scripts\workflows\jobs\steps\icu\build-icu.cmd

      - name: Install ICU
        run: scripts\workflows\jobs\steps\icu\install-icu.cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: icu
          path: ${{ env.SW_INSTALL_DIR }}

  curl:

    runs-on: windows-latest
    needs: [zlib]
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Build Environment
        run: |
          call scripts\tools\init-build.cmd
          call scripts\workflows\jobs\steps\curl\configure-build-environment.cmd

      - name: Checkout curl
        uses: actions/checkout@v2
        with:
          repository: 'curl/curl'
          ref: '${{ env.SW_CURL_REF }}'
          fetch-depth: 1
          path: '${{ env.SW_CURL_SOURCES_DIR }}'

      - name: Download zlib
        uses: actions/download-artifact@v1
        with:
          name: zlib
          path: '${{ env.SW_ARTIFACTS_DIR }}'

      - name: Configure curl
        run: scripts\workflows\jobs\steps\curl\configure-curl.cmd

      - name: Build curl
        run: scripts\workflows\jobs\steps\curl\build-curl.cmd

      - name: Install curl
        run: scripts\workflows\jobs\steps\curl\install-curl.cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: curl
          path: ${{ env.SW_INSTALL_DIR }}

  libxml2:

    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Configure Build Environment
        run: |
          call scripts\tools\init-build.cmd
          call scripts\workflows\jobs\steps\libxml2\configure-build-environment.cmd

      - name: Checkout libxml2
        uses: actions/checkout@v2
        with:
          repository: 'compnerd/libxml2'
          ref: '${{ env.SW_XML2_REF }}'
          fetch-depth: 1
          path: '${{ env.SW_XML2_SOURCES_DIR }}'

      - name: Configure libxml2
        run: scripts\workflows\jobs\steps\libxml2\configure-libxml2.cmd

      - name: Build libxml2
        run: scripts\workflows\jobs\steps\libxml2\build-libxml2.cmd

      - name: Install libxml2
        run: scripts\workflows\jobs\steps\libxml2\install-libxml2.cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: libxml2
          path: ${{ env.SW_INSTALL_DIR }}

  zlib:

    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Configure Build Environment
        run: |
          call scripts\tools\init-build.cmd
          call scripts\workflows\jobs\steps\zlib\configure-build-environment.cmd

      - name: Checkout zlib
        uses: actions/checkout@v2
        with:
          repository: 'madler/zlib'
          ref: '${{ env.SW_ZLIB_REF }}'
          fetch-depth: 1
          path: '${{ env.SW_ZLIB_SOURCES_DIR }}'

      - name: Configure zlib
        run: scripts\workflows\jobs\steps\zlib\configure-zlib.cmd

      - name: Build zlib
        run: scripts\workflows\jobs\steps\zlib\build-zlib.cmd

      - name: Install zlib
        run: scripts\workflows\jobs\steps\zlib\install-zlib.cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: zlib
          path: ${{ env.SW_INSTALL_DIR }}

  toolchain:

    runs-on: windows-latest
    needs: [icu]
    strategy:
      fail-fast: false
      matrix:
        patch: [clean, no-objc]
        include:
          - patch: clean
            enable-no-objc-patch: NO
          - patch: no-objc
            enable-no-objc-patch: YES

    defaults:
      run:
        shell: cmd

    env:
      SW_OBJC_PATCH_ENABLED: ${{ matrix.enable-no-objc-patch }}

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.x

      - name: Configure Build Environment
        run: |
          set SW_PYTHON_DIR=%pythonLocation%
          call scripts\tools\init-build.cmd
          call scripts\workflows\jobs\steps\toolchain\configure-build-environment.cmd

      - name: Configure Git
        run: scripts\workflows\jobs\steps\toolchain\configure-git.cmd

      - name: Checkout LLVM
        uses: actions/checkout@v2
        with:
          repository: 'apple/llvm-project'
          ref: ${{ env.SW_LLVM_REF }}
          fetch-depth: 1
          path: '${{ env.SW_LLVM_PROJECT_SOURCES_DIR }}'

      - name: Checkout cmark
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-cmark'
          ref: ${{ env.SW_CMARK_REF }}
          fetch-depth: 1
          path: '${{ env.SW_CMARK_SOURCES_DIR }}'

      - name: Checkout libdispatch
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-corelibs-libdispatch'
          ref: ${{ env.SW_DISPATCH_REF }}
          fetch-depth: 1
          path: '${{ env.SW_DISPATCH_SOURCES_DIR }}'

      - name: Checkout swift
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift'
          ref: ${{ env.SW_SWIFT_REF }}
          fetch-depth: 1
          path: '${{ env.SW_SWIFT_SOURCES_DIR }}'

      - name: Download ICU
        uses: actions/download-artifact@v1
        with:
          name: icu
          path: '${{ env.SW_ARTIFACTS_DIR }}'

      - name: Collect Checkout Info
        run: |
          mkdir %GITHUB_WORKSPACE%\checkout
          git -C %SW_LLVM_PROJECT_SOURCES_DIR% rev-parse HEAD > %SW_WORKSPACE%\checkout\llvm-project.txt
          git -C %SW_CMARK_SOURCES_DIR% rev-parse HEAD > %SW_WORKSPACE%\checkout\swift-cmark.txt
          git -C %SW_SWIFT_SOURCES_DIR% rev-parse HEAD > %SW_WORKSPACE%\checkout\swift.txt
          git -C %SW_DISPATCH_SOURCES_DIR% rev-parse HEAD > %SW_WORKSPACE%\checkout\swift-corelibs-libdispatch.txt

      - name: Upload Checkout Info
        uses: actions/upload-artifact@v1
        with:
          name: checkout
          path: 'checkout'

      - name: Configure LLVM Build Tools
        run: scripts\workflows\jobs\steps\toolchain\configure-llvm-build-tools.cmd

      - name: Build LLVM Build Tools
        run: scripts\workflows\jobs\steps\toolchain\build-llvm-build-tools.cmd

      - name: Build Clang Build Tools
        run: scripts\workflows\jobs\steps\toolchain\build-clang-build-tools.cmd

      - name: Build LLDB Build Tools
        run: scripts\workflows\jobs\steps\toolchain\build-lldb-build-tools.cmd

      - name: Build Diagnostics Serialization Tools
        run: scripts\workflows\jobs\steps\toolchain\build-swift-serialize-diagnostics.cmd

      - name: Configure SDK Modules
        run: scripts\workflows\jobs\steps\toolchain\configure-sdk-modules.cmd

      - name: Configure Toolchain
        run: scripts\workflows\jobs\steps\toolchain\configure-toolchain.cmd

      - name: Build Toolchain
        run: scripts\workflows\jobs\steps\toolchain\build-toolchain.cmd

      - name: Install Toolchain
        run: scripts\workflows\jobs\steps\toolchain\install-toolchain.cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: toolchain-${{ matrix.patch }}
          path: ${{ env.SW_INSTALL_DIR }}

      - name: Configure Test Environment
        run: scripts\workflows\jobs\steps\toolchain\configure-test-environment.cmd

      - name: Check Swift
        continue-on-error: true
        run: scripts\workflows\jobs\steps\toolchain\check-swift.cmd

      - name: Check Windows Defender
        run: |
          sc query WinDefend

  sdk:

    runs-on: windows-latest
    needs: [curl, icu, libxml2, toolchain, zlib]
    defaults:
      run:
        shell: cmd

    env:
      SW_FOUNDATION_REF: 'main'
      SW_XCTEST_REF: 'main'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Checkout Info
        uses: actions/download-artifact@v1
        with:
          name: checkout
          path: '${{ env.SW_ARTIFACTS_DIR }}/checkout'

      - name: Read Checkout Info
        run: |
          set /p SW_LLVM_REF=< %SW_ARTIFACTS_DIR%\checkout\llvm-project.txt
          set /p SW_SWIFT_REF=< %SW_ARTIFACTS_DIR%\checkout\swift.txt
          set /p SW_DISPATCH_REF=< %SW_ARTIFACTS_DIR%\checkout\swift-corelibs-libdispatch.txt

          echo llvm-project rev is %SW_LLVM_REF%
          echo swift rev is %SW_SWIFT_REF%
          echo swift-corelibs-libdispatch rev is %SW_DISPATCH_REF%

          echo SW_LLVM_REF=%SW_LLVM_REF%>>%GITHUB_ENV%
          echo SW_SWIFT_REF=%SW_SWIFT_REF%>>%GITHUB_ENV%
          echo SW_DISPATCH_REF=%SW_DISPATCH_REF%>>%GITHUB_ENV%

      - name: Use Python 2.7.x
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 2.7.x

      - name: Configure Build Environment
        run: |
          set SW_PYTHON_DIR=%pythonLocation%
          call scripts\tools\init-build.cmd
          call scripts\workflows\jobs\steps\sdk\configure-build-environment.cmd

      - name: Configure Git
        run: scripts\workflows\jobs\steps\sdk\configure-git.cmd

      - name: Checkout LLVM
        uses: actions/checkout@v2
        with:
          repository: 'apple/llvm-project'
          ref: ${{ env.SW_LLVM_REF }}
          fetch-depth: 1
          path: '${{ env.SW_LLVM_PROJECT_SOURCES_DIR }}'

      - name: Checkout swift
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift'
          ref: ${{ env.SW_SWIFT_REF }}
          fetch-depth: 1
          path: '${{ env.SW_SWIFT_SOURCES_DIR }}'

      - name: Checkout libdispatch
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-corelibs-libdispatch'
          ref: ${{ env.SW_DISPATCH_REF }}
          fetch-depth: 1
          path: '${{ env.SW_DISPATCH_SOURCES_DIR }}'

      - name: Checkout foundation
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-corelibs-foundation'
          ref: ${{ env.SW_FOUNDATION_REF }}
          fetch-depth: 1
          path: '${{ env.SW_FOUNDATION_SOURCES_DIR }}'

      - name: Checkout xctest
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-corelibs-xctest'
          ref: ${{ env.SW_XCTEST_REF }}
          fetch-depth: 1
          path: '${{ env.SW_XCTEST_SOURCES_DIR }}'

      - name: Patch LLVM
        run: scripts\workflows\jobs\steps\toolchain\patch-llvm.cmd

      - name: Patch StdLib
        run: scripts\workflows\jobs\steps\sdk\patch-stdlib.cmd

      - name: Download ICU
        uses: actions/download-artifact@v1
        with:
          name: icu
          path: '${{ env.SW_ARTIFACTS_DIR }}'
      - name: Download curl
        uses: actions/download-artifact@v1
        with:
          name: curl
          path: '${{ env.SW_ARTIFACTS_DIR }}'
      - name: Download libxml2
        uses: actions/download-artifact@v1
        with:
          name: libxml2
          path: '${{ env.SW_ARTIFACTS_DIR }}'
      - name: Download zlib
        uses: actions/download-artifact@v1
        with:
          name: zlib
          path: '${{ env.SW_ARTIFACTS_DIR }}'
      - name: Download toolchain
        uses: actions/download-artifact@v1
        with:
          name: toolchain-clean
          path: '${{ env.SW_ARTIFACTS_DIR }}'

      - name: Configure SDK Modules
        run: scripts\workflows\jobs\steps\toolchain\configure-sdk-modules.cmd

      - name: Configure LLVM
        run:  scripts\workflows\jobs\steps\sdk\configure-llvm.cmd

      - name: Configure Swift Standard Library
        run: scripts\workflows\jobs\steps\sdk\configure-swift-stdlib.cmd

      - name: Build Swift Standard Library
        run: scripts\workflows\jobs\steps\sdk\build-swift-stdlib.cmd

      - name: Configure libdispatch
        run: scripts\workflows\jobs\steps\sdk\configure-libdispatch.cmd

      - name: Build libdispatch
        run: scripts\workflows\jobs\steps\sdk\build-libdispatch.cmd

      - name: Configure Foundation
        run: scripts\workflows\jobs\steps\sdk\configure-foundation.cmd

      - name: Build Foundation
        run: scripts\workflows\jobs\steps\sdk\build-foundation.cmd

      - name: Configure XCTest
        run: scripts\workflows\jobs\steps\sdk\configure-xctest.cmd

      - name: Build XCTest
        run: scripts\workflows\jobs\steps\sdk\build-xctest.cmd

      - name: Install Swift Standard Library
        run: scripts\workflows\jobs\steps\sdk\install-swift-stdlib.cmd

      - name: Install Foundation
        run: scripts\workflows\jobs\steps\sdk\install-foundation.cmd

      - name: Install XCTest
        run: scripts\workflows\jobs\steps\sdk\install-xctest.cmd

      - name: Install libdispatch
        run: scripts\workflows\jobs\steps\sdk\install-libdispatch.cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: sdk
          path: ${{ env.SW_INSTALL_DIR }}

      - name: Configure libdispatch Tests
        run: scripts\workflows\jobs\steps\sdk\configure-libdispatch-tests.cmd

      - name: Build libdispatch Tests
        run: scripts\workflows\jobs\steps\sdk\build-libdispatch.cmd

      - name: Test libdispatch
        continue-on-error: true
        run: scripts\workflows\jobs\steps\sdk\test-libdispatch.cmd

      - name: Configure Foundation Test Environment
        run: scripts\workflows\jobs\steps\sdk\configure-foundation-test-environment.cmd

      - name: Configure Foundation Tests
        run: scripts\workflows\jobs\steps\sdk\configure-foundation-tests.cmd

      - name: Build Foundation Tests
        run: scripts\workflows\jobs\steps\sdk\build-foundation.cmd

      - name: Test Foundation (CTest)
        continue-on-error: true
        run: scripts\workflows\jobs\steps\sdk\test-foundation-ctest.cmd

      - name: Test Foundation (XCTest)
        continue-on-error: true
        run: scripts\workflows\jobs\steps\sdk\test-foundation-xctest.cmd
