name: swift-win-x64-vs2019
on: [push]

env:
  SW_CURL_VERSION: development
  SW_ICU_VERSION: 64
  SW_XML2_VERSION: development
  SW_ZLIB_VERSION: 1.2.11

jobs:
  icu:

    runs-on: windows-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Checkout ICU
        uses: actions/checkout@v2
        with:
          repository: 'unicode-org/icu'
          ref: 'maint/maint-64'
          fetch-depth: 1
          path: 'icu'
      - name: Configure Build Environment
        shell: cmd
        run: |
          call .github\workflows\vsenv.cmd -arch=x64 -host_arch=x64
          
          set SW_INSTALL_PATH=%GITHUB_WORKSPACE%\i\Library\icu-%SW_ICU_VERSION%\usr
          echo ::set-env name=SW_INSTALL_PATH::%SW_INSTALL_PATH%

          copy %GITHUB_WORKSPACE%\cmake\ICU\CMakeLists.txt icu\icu4c

      - name: Configure ICU
        shell: cmd
        run: |
          subst T: "%GITHUB_WORKSPACE%\icu\icu4c"
          cmake^
           -G Ninja^
           -S T:\^
           -B %GITHUB_WORKSPACE%\b^
           -C %GITHUB_WORKSPACE%\cmake\caches\windows-x86_64.cmake^
           -DCMAKE_BUILD_TYPE=MinSizeRel^
           -DCMAKE_INSTALL_PREFIX=%SW_INSTALL_PATH%^
           -DBUILD_SHARED_LIBS=YES^
           -DBUILD_TOOLS=YES

      - name: Build ICU
        shell: cmd
        run: |
          cmake --build %GITHUB_WORKSPACE%\b
      - name: Install ICU
        shell: cmd
        run: |
          cmake --build %GITHUB_WORKSPACE%\b --target install
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: icu
          path: i

  curl:

    runs-on: windows-latest
    needs: [zlib]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout curl
        uses: actions/checkout@v2
        with:
          repository: 'curl/curl'
          ref: 'master'
          fetch-depth: 1
          path: 'curl'
      - name: Download zlib
        uses: actions/download-artifact@v1
        with:
          name: zlib
          path: 'a'
      - name: Configure Build Environment
        shell: cmd
        run: |
          call .github\workflows\vsenv.cmd -arch=x64 -host_arch=x64
          
          set SW_ARTIFACTS_PATH=%GITHUB_WORKSPACE%\a
          set SW_INSTALL_PATH=%GITHUB_WORKSPACE%\i\Library\libcurl-%SW_CURL_VERSION%\usr
          set SW_ZLIB_PATH=%SW_ARTIFACTS_PATH%\Library\zlib-%SW_ZLIB_VERSION%
          
          echo ::set-env name=SW_ARTIFACTS_PATH::%SW_ARTIFACTS_PATH%
          echo ::set-env name=SW_INSTALL_PATH::%SW_INSTALL_PATH%
          echo ::set-env name=SW_ZLIB_PATH::%SW_ZLIB_PATH%

      - name: Configure curl
        shell: cmd
        run: |
          cmake^
           -G Ninja^
           -S %GITHUB_WORKSPACE%\curl^
           -B %GITHUB_WORKSPACE%\b^
           -C %GITHUB_WORKSPACE%\cmake\caches\windows-x86_64.cmake^
           -C %GITHUB_WORKSPACE%\cmake\caches\curl.cmake^
           -DCMAKE_BUILD_TYPE=MinSizeRel^
           -DCMAKE_INSTALL_PREFIX=%SW_INSTALL_PATH%^
           -DZLIB_ROOT=%SW_ZLIB_PATH%\usr^
           -DBUILD_SHARED_LIBS=NO^
           -DBUILD_TESTING=NO

      - name: Build curl
        shell: cmd
        run: |
          cmake --build %GITHUB_WORKSPACE%\b
      - name: Install zlib
        shell: cmd
        run: |
          cmake --build %GITHUB_WORKSPACE%\b --target install
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: curl
          path: i
          
  libxml2:

    runs-on: windows-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Checkout libxml2
        uses: actions/checkout@v2
        with:
          repository: 'compnerd/libxml2'
          ref: 'cmake'
          fetch-depth: 1
          path: 'libxml2'
      - name: Configure Build Environment
        shell: cmd
        run: |
          call .github\workflows\vsenv.cmd -arch=x64 -host_arch=x64
          
          set SW_INSTALL_PATH=%GITHUB_WORKSPACE%\i\Library\libxml2-%SW_XML2_VERSION%\usr
          echo ::set-env name=SW_INSTALL_PATH::%SW_INSTALL_PATH%

      - name: Configure libxml2
        shell: cmd
        run: |
          cmake^
           -G Ninja^
           -S %GITHUB_WORKSPACE%\libxml2^
           -B %GITHUB_WORKSPACE%\b^
           -C %GITHUB_WORKSPACE%\cmake\caches\windows-x86_64.cmake^
           -C %GITHUB_WORKSPACE%\cmake\caches\libxml2.cmake^
           -DCMAKE_BUILD_TYPE=MinSizeRel^
           -DCMAKE_INSTALL_PREFIX=%SW_INSTALL_PATH%^
           -DBUILD_SHARED_LIBS=NO^
           -DBUILD_TESTING=NO

      - name: Build libxml2
        shell: cmd
        run: |
          cmake --build %GITHUB_WORKSPACE%\b
      - name: Install libxml2
        shell: cmd
        run: |
          cmake --build %GITHUB_WORKSPACE%\b --target install
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: libxml2
          path: i

  zlib:

    runs-on: windows-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Checkout zlib
        uses: actions/checkout@v2
        with:
          repository: 'madler/zlib'
          ref: 'refs/tags/v1.2.11'
          fetch-depth: 1
          path: 'zlib'
      - name: Configure Build Environment
        shell: cmd
        run: |
          call .github\workflows\vsenv.cmd -arch=x64 -host_arch=x64
          
          set SW_INSTALL_PATH=%GITHUB_WORKSPACE%\i\Library\zlib-%SW_ZLIB_VERSION%\usr
          echo ::set-env name=SW_INSTALL_PATH::%SW_INSTALL_PATH%

      - name: Configure zlib
        shell: cmd
        run: |
          cmake^
           -G Ninja^
           -S %GITHUB_WORKSPACE%\zlib^
           -B %GITHUB_WORKSPACE%\b^
           -C %GITHUB_WORKSPACE%\cmake\caches\windows-x86_64.cmake^
           -DCMAKE_BUILD_TYPE=MinSizeRel^
           -DCMAKE_INSTALL_PREFIX=%SW_INSTALL_PATH%^
           -DBUILD_SHARED_LIBS=NO^
           -DBUILD_TESTING=NO

      - name: Build zlib
        shell: cmd
        run: |
          cmake --build %GITHUB_WORKSPACE%\b
      - name: Install zlib
        shell: cmd
        run: |
          cmake --build %GITHUB_WORKSPACE%\b --target install
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: zlib
          path: i

  toolchain:

    runs-on: windows-latest
    needs: [icu]
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Configure Git
        shell: cmd
        run: |
          git config --global --add core.autocrlf false
          git config --global --add core.symlinks true

      - name: Checkout LLVM
        uses: actions/checkout@v2
        with:
          repository: 'apple/llvm-project'
          ref: 'swift/master'
          fetch-depth: 1
          path: 's/toolchain' 
      - name: Checkout cmark
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-cmark'
          ref: 'master'
          fetch-depth: 1
          path: 's/toolchain/cmark' 
      - name: Checkout libdispatch
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-corelibs-libdispatch'
          ref: 'master'
          fetch-depth: 1
          path: 's/swift-corelibs-libdispatch' 
      - name: Checkout swift
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift'
          ref: 'master'
          fetch-depth: 1
          path: 's/toolchain/swift'
      - name: Download ICU
        uses: actions/download-artifact@v1
        with:
          name: icu
          path: 'a'
      - name: Configure Build Environment
        shell: cmd
        run: |
          call .github\workflows\vsenv.cmd -arch=x64 -host_arch=x64
          
          set SW_ARTIFACTS_PATH=%GITHUB_WORKSPACE%\a
          set SW_SOURCES_PATH=%GITHUB_WORKSPACE%\s
          set SW_BINARIES_PATH=%GITHUB_WORKSPACE%\b
          set SW_INSTALL_PATH=%GITHUB_WORKSPACE%\i\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain
          set SW_ICU_PATH=%SW_ARTIFACTS_PATH%\Library\icu-%SW_ICU_VERSION%
          
          echo ::set-env name=SW_ARTIFACTS_PATH::%SW_ARTIFACTS_PATH%
          echo ::set-env name=SW_SOURCES_PATH::%SW_SOURCES_PATH%
          echo ::set-env name=SW_BINARIES_PATH::%SW_BINARIES_PATH%
          echo ::set-env name=SW_INSTALL_PATH::%SW_INSTALL_PATH%
          echo ::set-env name=SW_ICU_PATH::%SW_ICU_PATH%

      - name: Configure LLVM Build Tools
        shell: cmd
        run: |
          cmake^
           -G Ninja^
           -S %SW_SOURCES_PATH%\toolchain\llvm^
           -B %SW_BINARIES_PATH%\llvm-tools^
           -C %GITHUB_WORKSPACE%\cmake\caches\windows-x86_64.cmake^
           -DCMAKE_BUILD_TYPE=Release^
           -DLLVM_ENABLE_ASSERTIONS=NO^
           -DLLVM_ENABLE_PROJECTS="clang;lldb"^
           -DLLDB_DISABLE_PYTHON=YES^
           -DLLDB_INCLUDE_TESTS=NO

      - name: Build LLVM Build Tools
        shell: cmd
        run: |
          cmake --build %SW_BINARIES_PATH%\llvm-tools --target llvm-tblgen
      - name: Build Clang Build Tool
        shell: cmd
        run: |
          cmake --build %SW_BINARIES_PATH%\llvm-tools --target clang-tblgen
      - name: Build LLDB Build Tools
        shell: cmd
        run: |
          cmake --build %SW_BINARIES_PATH%\llvm-tools --target lldb-tblgen
      - name: Configure SDK
        shell: cmd
        run: |
          copy %SW_SOURCES_PATH%\toolchain\swift\stdlib\public\Platform\ucrt.modulemap "%UniversalCRTSdkDir%\Include\%UCRTVersion%\ucrt\module.modulemap"
          copy %SW_SOURCES_PATH%\toolchain\swift\stdlib\public\Platform\visualc.modulemap "%VCToolsInstallDir%\include\module.modulemap"
          copy %SW_SOURCES_PATH%\toolchain\swift\stdlib\public\Platform\visualc.apinotes "%VCToolsInstallDir%\include\visualc.apinotes"
          copy %SW_SOURCES_PATH%\toolchain\swift\stdlib\public\Platform\winsdk.modulemap "%UniversalCRTSdkDir%\Include\%UCRTVersion%\um\module.modulemap"

      - name: Use Python 2.7.x
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 2.7.x
      - name: Expose Build Tools
        shell: cmd
        run: |
          FOR /F "tokens=*" %%g IN ('where python') do (SET SW_PYTHON_PATH=%%g)
          
          echo ::set-env name=SW_PYTHON_PATH::%SW_PYTHON_PATH%
          
          echo ::set-env name=LLVM_TABLEGEN::%SW_BINARIES_PATH%\llvm-tools\bin\llvm-tblgen.exe
          echo ::set-env name=CLANG_TABLEGEN::%SW_BINARIES_PATH%\llvm-tools\bin\clang-tblgen.exe
          echo ::set-env name=LLDB_TABLEGEN::%SW_BINARIES_PATH%\llvm-tools\bin\lldb-tblgen.exe

      - name: Configure Toolchain
        shell: cmd
        run: |
          cmake^
           -G Ninja^
           -S %SW_SOURCES_PATH%\toolchain\llvm^
           -B %SW_BINARIES_PATH%\toolchain^
           -C %GITHUB_WORKSPACE%\cmake\caches\windows-x86_64.cmake^
           -C %GITHUB_WORKSPACE%\cmake\caches\org.lxbndr.dt.cmake^
           -DCMAKE_BUILD_TYPE=Release^
           -DCMAKE_INSTALL_PREFIX=%SW_INSTALL_PATH%\usr^
           -DLLDB_FRAMEWORK_INSTALL_DIR=%SW_INSTALL_PATH%\Library\PrivateFrameworks^
           -DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-windows-msvc^
           -DLLVM_USE_HOST_TOOLS=NO^
           -DLLVM_TABLEGEN=%LLVM_TABLEGEN%^
           -DCLANG_TABLEGEN=%CLANG_TABLEGEN%^
           -DLLDB_TABLEGEN=%LLDB_TABLEGEN%^
           -DSWIFT_PATH_TO_LIBDISPATCH_SOURCE=%SW_SOURCES_PATH%\swift-corelibs-libdispatch^
           -DLLVM_ENABLE_LIBEDIT=NO^
           -DLLVM_PARALLEL_LINK_JOBS=2^
           -DPYTHON_EXECUTABLE=%pythonLocation%\python.exe^
           -DLLDB_DISABLE_PYTHON=YES^
           -DSWIFT_WINDOWS_x86_64_ICU_UC_INCLUDE=%SW_ICU_PATH%\usr\include\unicode^
           -DSWIFT_WINDOWS_x86_64_ICU_UC=%SW_ICU_PATH%\usr\lib\icuuc%SW_ICU_VERSION%.lib^
           -DSWIFT_WINDOWS_x86_64_ICU_I18N_INCLUDE=%SW_ICU_PATH%\usr\include^
           -DSWIFT_WINDOWS_x86_64_ICU_I18N=%SW_ICU_PATH%\usr\lib\icuin%SW_ICU_VERSION%.lib^
           -DSWIFT_PARALLEL_LINK_JOBS=2^
           -DSWIFT_BUILD_DYNAMIC_STDLIB=YES^
           -DSWIFT_BUILD_DYNAMIC_SDK_OVERLAY=YES

      - name: Build Toolchain
        shell: cmd
        run: |
          cmake --build %SW_BINARIES_PATH%\toolchain --target distribution

      - name: Install Toolchain
        shell: cmd
        run: |
          cmake --build %SW_BINARIES_PATH%\toolchain --target install-distribution

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: toolchain
          path: i

      - name: Prepare Test Environment
        shell: cmd
        run: |
          echo ::set-env name=PATH::%SW_ICU_PATH%\usr\bin;%SW_INSTALL_PATH%\usr\bin;%PATH%;%ProgramFiles%\Git\usr\bin

      - name: Check Swift
        continue-on-error: true
        shell: cmd
        run: |
          cmake --build %SW_BINARIES_PATH%\toolchain --target check-swift

  sdk:

    runs-on: windows-latest
    needs: [curl, icu, libxml2, toolchain, zlib]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Git
        shell: cmd
        run: |
          git config --global --add core.autocrlf false
          git config --global --add core.symlinks true
      - name: Checkout LLVM
        uses: actions/checkout@v2
        with:
          repository: 'apple/llvm-project'
          ref: 'swift/master'
          fetch-depth: 1
      - name: Checkout swift
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift'
          ref: 'master'
          fetch-depth: 1
      - name: Checkout libdispatch
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-corelibs-libdispatch'
          ref: 'master'
          fetch-depth: 1
      - name: Checkout foundation
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-corelibs-foundation'
          ref: 'master'
          fetch-depth: 1
      - name: Checkout xctest
        uses: actions/checkout@v2
        with:
          repository: 'apple/swift-corelibs-xctest'
          ref: 'master'
          fetch-depth: 1
      - name: Download ICU
        uses: actions/download-artifact@v1
        with:
          name: icu
          path: 'a'
      - name: Download curl
        uses: actions/download-artifact@v1
        with:
          name: curl
          path: 'a'
      - name: Download libxml2
        uses: actions/download-artifact@v1
        with:
          name: libxml2
          path: 'a'
      - name: Download zlib
        uses: actions/download-artifact@v1
        with:
          name: zlib
          path: 'a'
      - name: Download toolchain
        uses: actions/download-artifact@v1
        with:
          name: toolchain
          path: 'a'
      - name: Configure Build Environment
        shell: cmd
        run: |
          call .github\workflows\vsenv.cmd -arch=x64 -host_arch=x64
          
          set SW_ARTIFACTS_PATH=%GITHUB_WORKSPACE%\a
          set SW_SOURCES_PATH=%GITHUB_WORKSPACE%
          set SW_BINARIES_PATH=%GITHUB_WORKSPACE%\b
          
          set SW_PLATFORM_PATH=%GITHUB_WORKSPACE%\i\Library\Developer\Platforms\Windows.platform
          
          set SW_SDK_PATH=%SW_PLATFORM_PATH%\Developer\SDKs\Windows.sdk
          set SW_INSTALL_PATH=%SW_SDK_PATH%\usr
          set SW_XCTEST_INSTALL_PATH=%SW_PLATFORM_PATH%\Developer\Library\XCTest-development\usr
          
          set SW_TOOLCHAIN_PATH=%SW_ARTIFACTS_PATH%\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain
          set SW_CURL_PATH=%SW_ARTIFACTS_PATH%\Library\libcurl-%SW_CURL_VERSION%
          set SW_ICU_PATH=%SW_ARTIFACTS_PATH%\Library\icu-%SW_ICU_VERSION%
          set SW_XML2_PATH=%SW_ARTIFACTS_PATH%\Library\libxml2-%SW_XML2_VERSION%
          set SW_ZLIB_PATH=%SW_ARTIFACTS_PATH%\Library\zlib-%SW_ZLIB_VERSION%
          
          set PATH=%SW_TOOLCHAIN_PATH%\usr\bin
          
          
          echo ::set-env name=SW_ARTIFACTS_PATH::%SW_ARTIFACTS_PATH%
          echo ::set-env name=SW_SOURCES_PATH::%SW_SOURCES_PATH%
          echo ::set-env name=SW_BINARIES_PATH::%SW_BINARIES_PATH%
          
          echo ::set-env name=SW_PLATFORM_PATH::%SW_PLATFORM_PATH%
          
          echo ::set-env name=SW_SDK_PATH::%SW_SDK_PATH%
          echo ::set-env name=SW_INSTALL_PATH::%SW_INSTALL_PATH%
          echo ::set-env name=SW_XCTEST_INSTALL_PATH::%SW_XCTEST_INSTALL_PATH%
          
          echo ::set-env name=SW_CURL_PATH::%SW_CURL_PATH%
          echo ::set-env name=SW_ICU_PATH::%SW_ICU_PATH%
          echo ::set-env name=SW_XML2_PATH::%SW_XML2_PATH%
          echo ::set-env name=SW_ZLIB_PATH::%SW_ZLIB_PATH%
          
          echo ::set-env name=PATH::%PATH%
          
